In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv("../data/predtrain.csv")
test = pd.read_csv("../data/predtest.csv")

In [3]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [4]:
test.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

In [31]:
train["Churn"].value_counts()

Churn
No     460377
Yes    133817
Name: count, dtype: int64

In [30]:
train["MonthlyCharges"].value_counts()

MonthlyCharges
20.05     7436
19.95     5718
19.70     5705
20.00     5493
19.85     5114
          ...
28.20        1
37.15        1
18.45        1
112.05       1
46.15        1
Name: count, Length: 1921, dtype: int64

In [29]:
train["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             215372
Credit card (automatic)      133705
Mailed check                 123757
Bank transfer (automatic)    121360
Name: count, dtype: int64

In [28]:
train["PaperlessBilling"].value_counts()

PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

In [27]:
train["Contract"].value_counts()

Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

In [26]:
train["StreamingMovies"].value_counts()

StreamingMovies
Yes                    241435
No                     212032
No internet service    140727
Name: count, dtype: int64

In [25]:
train["StreamingTV"].value_counts()

StreamingTV
Yes                    240301
No                     213166
No internet service    140727
Name: count, dtype: int64

In [24]:
train["TechSupport"].value_counts()

TechSupport
No                     288571
Yes                    164896
No internet service    140727
Name: count, dtype: int64

In [23]:
train["DeviceProtection"].value_counts()

DeviceProtection
No                     247377
Yes                    206090
No internet service    140727
Name: count, dtype: int64

In [22]:
train["OnlineBackup"].value_counts()

OnlineBackup
No                     250083
Yes                    203384
No internet service    140727
Name: count, dtype: int64

In [21]:
train["OnlineSecurity"].value_counts()

OnlineSecurity
No                     289474
Yes                    163993
No internet service    140727
Name: count, dtype: int64

In [20]:
train["InternetService"].value_counts()

InternetService
Fiber optic    272386
DSL            181081
No             140727
Name: count, dtype: int64

In [19]:
train["MultipleLines"].value_counts()

MultipleLines
No                  283384
Yes                 274509
No phone service     36301
Name: count, dtype: int64

In [18]:
train["PhoneService"].value_counts()

PhoneService
Yes    557893
No      36301
Name: count, dtype: int64

In [17]:
train["tenure"].value_counts()

tenure
72    56411
1     29182
71    20763
2     16766
3     13478
      ...
40     4203
21     3862
44     3496
39     3396
36     2562
Name: count, Length: 72, dtype: int64

In [16]:
train["Dependents"].value_counts()

Dependents
No     414362
Yes    179832
Name: count, dtype: int64

In [15]:
train["Partner"].value_counts()

Partner
Yes    309554
No     284640
Name: count, dtype: int64

In [12]:
train["gender"].value_counts()

gender
Female    298738
Male      295456
Name: count, dtype: int64

In [14]:
train["SeniorCitizen"].value_counts()

SeniorCitizen
0    526395
1     67799
Name: count, dtype: int64

In [37]:
train["Churn"].dtype



train["Churn"]= train["Churn"].map({"Yes":1, "No":0})

In [43]:
cat= {"Electronic check":1, "Credit card (automatic)": 2, "Mailed check":3, "Bank transfer (automatic)":4}

train["PaymentMethod"] = train["PaymentMethod"].map(cat)

In [45]:
train["PaperlessBilling"].value_counts()

PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

In [46]:
cat = {"Yes":1, "No":0}
train["PaperlessBilling"] = train["PaperlessBilling"].map(cat)

In [48]:
train["Contract"].value_counts()

Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

In [51]:
cat = {"Month-to-month":0, "One year": 1, "Two year":2}
train["Contract"] = train["Contract"].map(cat)

In [52]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  str
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  str
 4   Dependents        594194 non-null  str
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  str
 7   MultipleLines     594194 non-null  str
 8   InternetService   594194 non-null  str
 9   OnlineSecurity    594194 non-null  str
 10  OnlineBackup      594194 non-null  str
 11  DeviceProtection  594194 non-null  str
 12  TechSupport       594194 non-null  str
 13  StreamingTV       594194 non-null  str
 14  StreamingMovies   594194 non-null  str
 15  Contract          594194 non-null  int64
 16  PaperlessBilling  594194 non-null  int64
 17  PaymentMethod     594194 non-null  int64
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  int64
dtypes: float64(2), int64(7), str(12)
memory usage: 95.2 MB

In [5]:
train.isnull().sum()

id                  0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
train.describe()

,id,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000
mean,297096.500000,0.114102,36.577258,65.866223,2494.377057
std,171529.177263,0.317936,25.061922,31.067444,2353.916710
min,0.000000,0.000000,1.000000,18.250000,18.800000
25%,148548.250000,0.000000,12.000000,29.900000,639.650000
50%,297096.500000,0.000000,35.000000,74.100000,1433.650000
75%,445644.750000,0.000000,62.000000,90.800000,4263.800000
max,594193.000000,1.000000,72.000000,118.750000,8684.800000